# Generated by Django 2.1.5 on 2023-03-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.CharField(default='snogbog', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='description_text',
            field=models.CharField(default='21/03/2023', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='newstitle',
            field=models.CharField(default="It's hella chilly, wear a jacket", max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
